### ISSUE TITLE
About the new pull request

### ISSUE THREAD

**Issue by dorukgezici** [swappsco/django-wordpress-api#4]
Hey, are you thinking about merging that pull request soon? I couldn't make the master branch work with latest WP and Django.

**Comment by dorukgezici** [comment]
Also the static files (wordpress.css&js) are empty in the repo

**Comment by cdvv7788** [comment]
@jlariza Can you review and merge as appropriate please?

**Comment by cdvv7788** [comment]
@dorukgezici Merged. We will create a new package shortly.
